server:
  port: ${PORT:8762}

spring:  
  application:
    name: edge-server
    
eureka: 
  instance:
    hostname: localhost
  client: 
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://127.0.0.1:8761/eureka/