server:  
  port: ${PORT:2228}

spring:  
  application:
    name: demo-service
  profiles: 
      active: "@spring.profiles.active@"
  mvc: 
    view: 
      prefix: "/" 
      suffix: ".html"      

management: 
    endpoints: 
        web: 
          exposure: 
            include: "*"