server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service
    profiles: 
        active: "@spring.profiles.active@"
    data: 
        mongodb: 
            database: rssreader
            host: localhost
            port: 27017

management: 
    endpoints: 
        web: 
          exposure: 
            include: "*"

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10