info:
  component: Zuul Server

spring:  
  application:
    name: gateway-server
  profiles: 
      active: "@spring.profiles.active@"
  main: 
    allow-bean-definition-overriding: true 

zuul:
  prefix: /api
  routes:
    account:
          path: /**
          serviceId: account-service
server:
  port: 8765

eureka:  
  client: 
    serviceUrl: 
      defaultZone: http://127.0.0.1:8761/eureka/, http://localhost:8762/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10
    
ribbon:
  eureka: 
    enabled: true
        
logging: 
  level: 
    ROOT: INFO
    org.springframework.web: TRACE   